/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package com.skaria.avro.model.aggregate;

@org.apache.avro.specific.AvroGenerated
public interface InvariantFailureProtocol {
  public static final org.apache.avro.Protocol PROTOCOL = org.apache.avro.Protocol.parse("{\"protocol\":\"InvariantFailureProtocol\",\"namespace\":\"com.skaria.avro.model.aggregate\",\"types\":[{\"type\":\"record\",\"name\":\"InvariantFailureRecord\",\"fields\":[{\"name\":\"invariantId\",\"type\":{\"type\":\"string\",\"avro.java.string\":\"String\"}},{\"name\":\"invariantName\",\"type\":{\"type\":\"string\",\"avro.java.string\":\"String\"}},{\"name\":\"externalDescription\",\"type\":{\"type\":\"string\",\"avro.java.string\":\"String\"}},{\"name\":\"internalDescription\",\"type\":{\"type\":\"string\",\"avro.java.string\":\"String\"}}]}],\"messages\":{}}");

  @org.apache.avro.specific.AvroGenerated
  public interface Callback extends InvariantFailureProtocol {
    public static final org.apache.avro.Protocol PROTOCOL = com.skaria.avro.model.aggregate.InvariantFailureProtocol.PROTOCOL;
  }
}