/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package com.skaria.avro.model;

@org.apache.avro.specific.AvroGenerated
public interface IdentifierProtocol {
  public static final org.apache.avro.Protocol PROTOCOL = org.apache.avro.Protocol.parse("{\"protocol\":\"IdentifierProtocol\",\"namespace\":\"com.skaria.avro.model\",\"types\":[{\"type\":\"record\",\"name\":\"Identifier\",\"fields\":[{\"name\":\"identifier\",\"type\":{\"type\":\"string\",\"avro.java.string\":\"String\"}}]}],\"messages\":{}}");

  @org.apache.avro.specific.AvroGenerated
  public interface Callback extends IdentifierProtocol {
    public static final org.apache.avro.Protocol PROTOCOL = com.skaria.avro.model.IdentifierProtocol.PROTOCOL;
  }
}