/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package com.skaria.avro.model.aggregate.domain;

@org.apache.avro.specific.AvroGenerated
public interface DomainAggregateProtocol {
  public static final org.apache.avro.Protocol PROTOCOL = org.apache.avro.Protocol.parse("{\"protocol\":\"DomainAggregateProtocol\",\"namespace\":\"com.skaria.avro.model.aggregate.domain\",\"types\":[{\"type\":\"record\",\"name\":\"SomeListId\",\"namespace\":\"com.skaria.avro.model\",\"fields\":[{\"name\":\"firstName\",\"type\":{\"type\":\"string\",\"avro.java.string\":\"String\"}},{\"name\":\"lastName\",\"type\":{\"type\":\"string\",\"avro.java.string\":\"String\"}}]},{\"type\":\"enum\",\"name\":\"Action\",\"namespace\":\"com.skaria.avro.model\",\"symbols\":[\"STOP\",\"GO\"]},{\"type\":\"record\",\"name\":\"SomeList\",\"namespace\":\"com.skaria.avro.model\",\"fields\":[{\"name\":\"id\",\"type\":\"SomeListId\"},{\"name\":\"firstName\",\"type\":{\"type\":\"string\",\"avro.java.string\":\"String\"}},{\"name\":\"lastName\",\"type\":{\"type\":\"string\",\"avro.java.string\":\"String\"}},{\"name\":\"middlename\",\"type\":[\"null\",{\"type\":\"string\",\"avro.java.string\":\"String\"}]},{\"name\":\"age\",\"type\":[\"null\",{\"type\":\"string\",\"avro.java.string\":\"String\"}]},{\"name\":\"action\",\"type\":\"Action\"}]},{\"type\":\"record\",\"name\":\"Person\",\"namespace\":\"com.skaria.avro.model\",\"fields\":[{\"name\":\"person\",\"type\":\"Person\"}]},{\"type\":\"record\",\"name\":\"DomainAggregateStateRecord\",\"fields\":[{\"name\":\"creationTimestamp\",\"type\":{\"type\":\"string\",\"avro.java.string\":\"String\"}},{\"name\":\"lastUpdatedTimestamp\",\"type\":{\"type\":\"string\",\"avro.java.string\":\"String\"}},{\"name\":\"person\",\"type\":[\"null\",\"com.skaria.avro.model.Person\"],\"default\":null},{\"name\":\"someList\",\"type\":[\"null\",{\"type\":\"map\",\"values\":\"com.skaria.avro.model.SomeList\",\"avro.java.string\":\"String\"}],\"default\":null}]}],\"messages\":{}}");

  @org.apache.avro.specific.AvroGenerated
  public interface Callback extends DomainAggregateProtocol {
    public static final org.apache.avro.Protocol PROTOCOL = com.skaria.avro.model.aggregate.domain.DomainAggregateProtocol.PROTOCOL;
  }
}