/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package com.skaria.avro.model.aggregate.domain;

import org.apache.avro.generic.GenericArray;
import org.apache.avro.specific.SpecificData;
import org.apache.avro.util.Utf8;
import org.apache.avro.message.BinaryMessageEncoder;
import org.apache.avro.message.BinaryMessageDecoder;
import org.apache.avro.message.SchemaStore;
import java.util.Optional;
@org.apache.avro.specific.AvroGenerated
public class ProcessSomeRecordCommandRecord extends org.apache.avro.specific.SpecificRecordBase implements org.apache.avro.specific.SpecificRecord {
  private static final long serialVersionUID = -4376413401033493938L;


  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"record\",\"name\":\"ProcessSomeRecordCommandRecord\",\"namespace\":\"com.skaria.avro.model.aggregate.domain\",\"fields\":[{\"name\":\"someRecord\",\"type\":{\"type\":\"record\",\"name\":\"SomeRecord\",\"namespace\":\"com.skaria.avro.model\",\"fields\":[{\"name\":\"identifier\",\"type\":{\"type\":\"record\",\"name\":\"Identifier\",\"fields\":[{\"name\":\"identifier\",\"type\":{\"type\":\"string\",\"avro.java.string\":\"String\"}}]}},{\"name\":\"Id\",\"type\":{\"type\":\"record\",\"name\":\"Id\",\"fields\":[{\"name\":\"id\",\"type\":{\"type\":\"string\",\"avro.java.string\":\"String\"}}]}},{\"name\":\"TIMESTAMP\",\"type\":{\"type\":\"long\",\"logicalType\":\"timestamp-millis\"}},{\"name\":\"RECEIVEDDATE\",\"type\":{\"type\":\"long\",\"logicalType\":\"timestamp-millis\"}},{\"name\":\"PRODUCEDDATE\",\"type\":{\"type\":\"long\",\"logicalType\":\"timestamp-millis\"}},{\"name\":\"POSITION\",\"type\":[\"null\",{\"type\":\"record\",\"name\":\"Location\",\"fields\":[{\"name\":\"latitude\",\"type\":\"double\"},{\"name\":\"longitude\",\"type\":\"double\"}]}]},{\"name\":\"MEASURE\",\"type\":[\"null\",\"int\"]}]}}]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }

  private static final SpecificData MODEL$ = new SpecificData();
  static {
    MODEL$.addLogicalTypeConversion(new org.apache.avro.data.TimeConversions.TimestampMillisConversion());
  }

  private static final BinaryMessageEncoder<ProcessSomeRecordCommandRecord> ENCODER =
      new BinaryMessageEncoder<>(MODEL$, SCHEMA$);

  private static final BinaryMessageDecoder<ProcessSomeRecordCommandRecord> DECODER =
      new BinaryMessageDecoder<>(MODEL$, SCHEMA$);

  /**
   * Return the BinaryMessageEncoder instance used by this class.
   * @return the message encoder used by this class
   */
  public static BinaryMessageEncoder<ProcessSomeRecordCommandRecord> getEncoder() {
    return ENCODER;
  }

  /**
   * Return the BinaryMessageDecoder instance used by this class.
   * @return the message decoder used by this class
   */
  public static BinaryMessageDecoder<ProcessSomeRecordCommandRecord> getDecoder() {
    return DECODER;
  }

  /**
   * Create a new BinaryMessageDecoder instance for this class that uses the specified {@link SchemaStore}.
   * @param resolver a {@link SchemaStore} used to find schemas by fingerprint
   * @return a BinaryMessageDecoder instance for this class backed by the given SchemaStore
   */
  public static BinaryMessageDecoder<ProcessSomeRecordCommandRecord> createDecoder(SchemaStore resolver) {
    return new BinaryMessageDecoder<>(MODEL$, SCHEMA$, resolver);
  }

  /**
   * Serializes this ProcessSomeRecordCommandRecord to a ByteBuffer.
   * @return a buffer holding the serialized data for this instance
   * @throws java.io.IOException if this instance could not be serialized
   */
  public java.nio.ByteBuffer toByteBuffer() throws java.io.IOException {
    return ENCODER.encode(this);
  }

  /**
   * Deserializes a ProcessSomeRecordCommandRecord from a ByteBuffer.
   * @param b a byte buffer holding serialized data for an instance of this class
   * @return a ProcessSomeRecordCommandRecord instance decoded from the given buffer
   * @throws java.io.IOException if the given bytes could not be deserialized into an instance of this class
   */
  public static ProcessSomeRecordCommandRecord fromByteBuffer(
      java.nio.ByteBuffer b) throws java.io.IOException {
    return DECODER.decode(b);
  }

  private com.skaria.avro.model.SomeRecord someRecord;

  /**
   * Default constructor.  Note that this does not initialize fields
   * to their default values from the schema.  If that is desired then
   * one should use <code>newBuilder()</code>.
   */
  public ProcessSomeRecordCommandRecord() {}

  /**
   * All-args constructor.
   * @param someRecord The new value for someRecord
   */
  public ProcessSomeRecordCommandRecord(com.skaria.avro.model.SomeRecord someRecord) {
    this.someRecord = someRecord;
  }

  @Override
  public org.apache.avro.specific.SpecificData getSpecificData() { return MODEL$; }

  @Override
  public org.apache.avro.Schema getSchema() { return SCHEMA$; }

  // Used by DatumWriter.  Applications should not call.
  @Override
  public java.lang.Object get(int field$) {
    switch (field$) {
    case 0: return someRecord;
    default: throw new IndexOutOfBoundsException("Invalid index: " + field$);
    }
  }

  // Used by DatumReader.  Applications should not call.
  @Override
  @SuppressWarnings(value="unchecked")
  public void put(int field$, java.lang.Object value$) {
    switch (field$) {
    case 0: someRecord = (com.skaria.avro.model.SomeRecord)value$; break;
    default: throw new IndexOutOfBoundsException("Invalid index: " + field$);
    }
  }

  /**
   * Gets the value of the 'someRecord' field.
   * @return The value of the 'someRecord' field.
   */
  public com.skaria.avro.model.SomeRecord getSomeRecord() {
    return someRecord;
  }

  /**
   * Gets the value of the 'someRecord' field as an Optional&lt;com.skaria.avro.model.SomeRecord&gt;.
   * @return The value wrapped in an Optional&lt;com.skaria.avro.model.SomeRecord&gt;.
   */
  public Optional<com.skaria.avro.model.SomeRecord> getOptionalSomeRecord() {
    return Optional.<com.skaria.avro.model.SomeRecord>ofNullable(someRecord);
  }

  /**
   * Sets the value of the 'someRecord' field.
   * @param value the value to set.
   */
  public void setSomeRecord(com.skaria.avro.model.SomeRecord value) {
    this.someRecord = value;
  }

  /**
   * Creates a new ProcessSomeRecordCommandRecord RecordBuilder.
   * @return A new ProcessSomeRecordCommandRecord RecordBuilder
   */
  public static com.skaria.avro.model.aggregate.domain.ProcessSomeRecordCommandRecord.Builder newBuilder() {
    return new com.skaria.avro.model.aggregate.domain.ProcessSomeRecordCommandRecord.Builder();
  }

  /**
   * Creates a new ProcessSomeRecordCommandRecord RecordBuilder by copying an existing Builder.
   * @param other The existing builder to copy.
   * @return A new ProcessSomeRecordCommandRecord RecordBuilder
   */
  public static com.skaria.avro.model.aggregate.domain.ProcessSomeRecordCommandRecord.Builder newBuilder(com.skaria.avro.model.aggregate.domain.ProcessSomeRecordCommandRecord.Builder other) {
    if (other == null) {
      return new com.skaria.avro.model.aggregate.domain.ProcessSomeRecordCommandRecord.Builder();
    } else {
      return new com.skaria.avro.model.aggregate.domain.ProcessSomeRecordCommandRecord.Builder(other);
    }
  }

  /**
   * Creates a new ProcessSomeRecordCommandRecord RecordBuilder by copying an existing ProcessSomeRecordCommandRecord instance.
   * @param other The existing instance to copy.
   * @return A new ProcessSomeRecordCommandRecord RecordBuilder
   */
  public static com.skaria.avro.model.aggregate.domain.ProcessSomeRecordCommandRecord.Builder newBuilder(com.skaria.avro.model.aggregate.domain.ProcessSomeRecordCommandRecord other) {
    if (other == null) {
      return new com.skaria.avro.model.aggregate.domain.ProcessSomeRecordCommandRecord.Builder();
    } else {
      return new com.skaria.avro.model.aggregate.domain.ProcessSomeRecordCommandRecord.Builder(other);
    }
  }

  /**
   * RecordBuilder for ProcessSomeRecordCommandRecord instances.
   */
  @org.apache.avro.specific.AvroGenerated
  public static class Builder extends org.apache.avro.specific.SpecificRecordBuilderBase<ProcessSomeRecordCommandRecord>
    implements org.apache.avro.data.RecordBuilder<ProcessSomeRecordCommandRecord> {

    private com.skaria.avro.model.SomeRecord someRecord;
    private com.skaria.avro.model.SomeRecord.Builder someRecordBuilder;

    /** Creates a new Builder */
    private Builder() {
      super(SCHEMA$, MODEL$);
    }

    /**
     * Creates a Builder by copying an existing Builder.
     * @param other The existing Builder to copy.
     */
    private Builder(com.skaria.avro.model.aggregate.domain.ProcessSomeRecordCommandRecord.Builder other) {
      super(other);
      if (isValidValue(fields()[0], other.someRecord)) {
        this.someRecord = data().deepCopy(fields()[0].schema(), other.someRecord);
        fieldSetFlags()[0] = other.fieldSetFlags()[0];
      }
      if (other.hasSomeRecordBuilder()) {
        this.someRecordBuilder = com.skaria.avro.model.SomeRecord.newBuilder(other.getSomeRecordBuilder());
      }
    }

    /**
     * Creates a Builder by copying an existing ProcessSomeRecordCommandRecord instance
     * @param other The existing instance to copy.
     */
    private Builder(com.skaria.avro.model.aggregate.domain.ProcessSomeRecordCommandRecord other) {
      super(SCHEMA$, MODEL$);
      if (isValidValue(fields()[0], other.someRecord)) {
        this.someRecord = data().deepCopy(fields()[0].schema(), other.someRecord);
        fieldSetFlags()[0] = true;
      }
      this.someRecordBuilder = null;
    }

    /**
      * Gets the value of the 'someRecord' field.
      * @return The value.
      */
    public com.skaria.avro.model.SomeRecord getSomeRecord() {
      return someRecord;
    }

    /**
      * Gets the value of the 'someRecord' field as an Optional&lt;com.skaria.avro.model.SomeRecord&gt;.
      * @return The value wrapped in an Optional&lt;com.skaria.avro.model.SomeRecord&gt;.
      */
    public Optional<com.skaria.avro.model.SomeRecord> getOptionalSomeRecord() {
      return Optional.<com.skaria.avro.model.SomeRecord>ofNullable(someRecord);
    }

    /**
      * Sets the value of the 'someRecord' field.
      * @param value The value of 'someRecord'.
      * @return This builder.
      */
    public com.skaria.avro.model.aggregate.domain.ProcessSomeRecordCommandRecord.Builder setSomeRecord(com.skaria.avro.model.SomeRecord value) {
      validate(fields()[0], value);
      this.someRecordBuilder = null;
      this.someRecord = value;
      fieldSetFlags()[0] = true;
      return this;
    }

    /**
      * Checks whether the 'someRecord' field has been set.
      * @return True if the 'someRecord' field has been set, false otherwise.
      */
    public boolean hasSomeRecord() {
      return fieldSetFlags()[0];
    }

    /**
     * Gets the Builder instance for the 'someRecord' field and creates one if it doesn't exist yet.
     * @return This builder.
     */
    public com.skaria.avro.model.SomeRecord.Builder getSomeRecordBuilder() {
      if (someRecordBuilder == null) {
        if (hasSomeRecord()) {
          setSomeRecordBuilder(com.skaria.avro.model.SomeRecord.newBuilder(someRecord));
        } else {
          setSomeRecordBuilder(com.skaria.avro.model.SomeRecord.newBuilder());
        }
      }
      return someRecordBuilder;
    }

    /**
     * Sets the Builder instance for the 'someRecord' field
     * @param value The builder instance that must be set.
     * @return This builder.
     */

    public com.skaria.avro.model.aggregate.domain.ProcessSomeRecordCommandRecord.Builder setSomeRecordBuilder(com.skaria.avro.model.SomeRecord.Builder value) {
      clearSomeRecord();
      someRecordBuilder = value;
      return this;
    }

    /**
     * Checks whether the 'someRecord' field has an active Builder instance
     * @return True if the 'someRecord' field has an active Builder instance
     */
    public boolean hasSomeRecordBuilder() {
      return someRecordBuilder != null;
    }

    /**
      * Clears the value of the 'someRecord' field.
      * @return This builder.
      */
    public com.skaria.avro.model.aggregate.domain.ProcessSomeRecordCommandRecord.Builder clearSomeRecord() {
      someRecord = null;
      someRecordBuilder = null;
      fieldSetFlags()[0] = false;
      return this;
    }

    @Override
    @SuppressWarnings("unchecked")
    public ProcessSomeRecordCommandRecord build() {
      try {
        ProcessSomeRecordCommandRecord record = new ProcessSomeRecordCommandRecord();
        if (someRecordBuilder != null) {
          try {
            record.someRecord = this.someRecordBuilder.build();
          } catch (org.apache.avro.AvroMissingFieldException e) {
            e.addParentField(record.getSchema().getField("someRecord"));
            throw e;
          }
        } else {
          record.someRecord = fieldSetFlags()[0] ? this.someRecord : (com.skaria.avro.model.SomeRecord) defaultValue(fields()[0]);
        }
        return record;
      } catch (org.apache.avro.AvroMissingFieldException e) {
        throw e;
      } catch (java.lang.Exception e) {
        throw new org.apache.avro.AvroRuntimeException(e);
      }
    }
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumWriter<ProcessSomeRecordCommandRecord>
    WRITER$ = (org.apache.avro.io.DatumWriter<ProcessSomeRecordCommandRecord>)MODEL$.createDatumWriter(SCHEMA$);

  @Override public void writeExternal(java.io.ObjectOutput out)
    throws java.io.IOException {
    WRITER$.write(this, SpecificData.getEncoder(out));
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumReader<ProcessSomeRecordCommandRecord>
    READER$ = (org.apache.avro.io.DatumReader<ProcessSomeRecordCommandRecord>)MODEL$.createDatumReader(SCHEMA$);

  @Override public void readExternal(java.io.ObjectInput in)
    throws java.io.IOException {
    READER$.read(this, SpecificData.getDecoder(in));
  }

}










