/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package com.skaria.avro.model.aggregate.domain;

import org.apache.avro.generic.GenericArray;
import org.apache.avro.specific.SpecificData;
import org.apache.avro.util.Utf8;
import org.apache.avro.message.BinaryMessageEncoder;
import org.apache.avro.message.BinaryMessageDecoder;
import org.apache.avro.message.SchemaStore;
import java.util.Optional;
@org.apache.avro.specific.AvroGenerated
public class UpdatePersonCommandRecord extends org.apache.avro.specific.SpecificRecordBase implements org.apache.avro.specific.SpecificRecord {
  private static final long serialVersionUID = -2099942577241774850L;


  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"record\",\"name\":\"UpdatePersonCommandRecord\",\"namespace\":\"com.skaria.avro.model.aggregate.domain\",\"fields\":[{\"name\":\"Person\",\"type\":{\"type\":\"record\",\"name\":\"Person\",\"namespace\":\"com.skaria.avro.model\",\"fields\":[{\"name\":\"person\",\"type\":\"Person\"}]}}]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }

  private static final SpecificData MODEL$ = new SpecificData();

  private static final BinaryMessageEncoder<UpdatePersonCommandRecord> ENCODER =
      new BinaryMessageEncoder<>(MODEL$, SCHEMA$);

  private static final BinaryMessageDecoder<UpdatePersonCommandRecord> DECODER =
      new BinaryMessageDecoder<>(MODEL$, SCHEMA$);

  /**
   * Return the BinaryMessageEncoder instance used by this class.
   * @return the message encoder used by this class
   */
  public static BinaryMessageEncoder<UpdatePersonCommandRecord> getEncoder() {
    return ENCODER;
  }

  /**
   * Return the BinaryMessageDecoder instance used by this class.
   * @return the message decoder used by this class
   */
  public static BinaryMessageDecoder<UpdatePersonCommandRecord> getDecoder() {
    return DECODER;
  }

  /**
   * Create a new BinaryMessageDecoder instance for this class that uses the specified {@link SchemaStore}.
   * @param resolver a {@link SchemaStore} used to find schemas by fingerprint
   * @return a BinaryMessageDecoder instance for this class backed by the given SchemaStore
   */
  public static BinaryMessageDecoder<UpdatePersonCommandRecord> createDecoder(SchemaStore resolver) {
    return new BinaryMessageDecoder<>(MODEL$, SCHEMA$, resolver);
  }

  /**
   * Serializes this UpdatePersonCommandRecord to a ByteBuffer.
   * @return a buffer holding the serialized data for this instance
   * @throws java.io.IOException if this instance could not be serialized
   */
  public java.nio.ByteBuffer toByteBuffer() throws java.io.IOException {
    return ENCODER.encode(this);
  }

  /**
   * Deserializes a UpdatePersonCommandRecord from a ByteBuffer.
   * @param b a byte buffer holding serialized data for an instance of this class
   * @return a UpdatePersonCommandRecord instance decoded from the given buffer
   * @throws java.io.IOException if the given bytes could not be deserialized into an instance of this class
   */
  public static UpdatePersonCommandRecord fromByteBuffer(
      java.nio.ByteBuffer b) throws java.io.IOException {
    return DECODER.decode(b);
  }

  private com.skaria.avro.model.Person Person;

  /**
   * Default constructor.  Note that this does not initialize fields
   * to their default values from the schema.  If that is desired then
   * one should use <code>newBuilder()</code>.
   */
  public UpdatePersonCommandRecord() {}

  /**
   * All-args constructor.
   * @param Person The new value for Person
   */
  public UpdatePersonCommandRecord(com.skaria.avro.model.Person Person) {
    this.Person = Person;
  }

  @Override
  public org.apache.avro.specific.SpecificData getSpecificData() { return MODEL$; }

  @Override
  public org.apache.avro.Schema getSchema() { return SCHEMA$; }

  // Used by DatumWriter.  Applications should not call.
  @Override
  public java.lang.Object get(int field$) {
    switch (field$) {
    case 0: return Person;
    default: throw new IndexOutOfBoundsException("Invalid index: " + field$);
    }
  }

  // Used by DatumReader.  Applications should not call.
  @Override
  @SuppressWarnings(value="unchecked")
  public void put(int field$, java.lang.Object value$) {
    switch (field$) {
    case 0: Person = (com.skaria.avro.model.Person)value$; break;
    default: throw new IndexOutOfBoundsException("Invalid index: " + field$);
    }
  }

  /**
   * Gets the value of the 'Person' field.
   * @return The value of the 'Person' field.
   */
  public com.skaria.avro.model.Person getPerson() {
    return Person;
  }

  /**
   * Gets the value of the 'Person' field as an Optional&lt;com.skaria.avro.model.Person&gt;.
   * @return The value wrapped in an Optional&lt;com.skaria.avro.model.Person&gt;.
   */
  public Optional<com.skaria.avro.model.Person> getOptionalPerson() {
    return Optional.<com.skaria.avro.model.Person>ofNullable(Person);
  }

  /**
   * Sets the value of the 'Person' field.
   * @param value the value to set.
   */
  public void setPerson(com.skaria.avro.model.Person value) {
    this.Person = value;
  }

  /**
   * Creates a new UpdatePersonCommandRecord RecordBuilder.
   * @return A new UpdatePersonCommandRecord RecordBuilder
   */
  public static com.skaria.avro.model.aggregate.domain.UpdatePersonCommandRecord.Builder newBuilder() {
    return new com.skaria.avro.model.aggregate.domain.UpdatePersonCommandRecord.Builder();
  }

  /**
   * Creates a new UpdatePersonCommandRecord RecordBuilder by copying an existing Builder.
   * @param other The existing builder to copy.
   * @return A new UpdatePersonCommandRecord RecordBuilder
   */
  public static com.skaria.avro.model.aggregate.domain.UpdatePersonCommandRecord.Builder newBuilder(com.skaria.avro.model.aggregate.domain.UpdatePersonCommandRecord.Builder other) {
    if (other == null) {
      return new com.skaria.avro.model.aggregate.domain.UpdatePersonCommandRecord.Builder();
    } else {
      return new com.skaria.avro.model.aggregate.domain.UpdatePersonCommandRecord.Builder(other);
    }
  }

  /**
   * Creates a new UpdatePersonCommandRecord RecordBuilder by copying an existing UpdatePersonCommandRecord instance.
   * @param other The existing instance to copy.
   * @return A new UpdatePersonCommandRecord RecordBuilder
   */
  public static com.skaria.avro.model.aggregate.domain.UpdatePersonCommandRecord.Builder newBuilder(com.skaria.avro.model.aggregate.domain.UpdatePersonCommandRecord other) {
    if (other == null) {
      return new com.skaria.avro.model.aggregate.domain.UpdatePersonCommandRecord.Builder();
    } else {
      return new com.skaria.avro.model.aggregate.domain.UpdatePersonCommandRecord.Builder(other);
    }
  }

  /**
   * RecordBuilder for UpdatePersonCommandRecord instances.
   */
  @org.apache.avro.specific.AvroGenerated
  public static class Builder extends org.apache.avro.specific.SpecificRecordBuilderBase<UpdatePersonCommandRecord>
    implements org.apache.avro.data.RecordBuilder<UpdatePersonCommandRecord> {

    private com.skaria.avro.model.Person Person;
    private com.skaria.avro.model.Person.Builder PersonBuilder;

    /** Creates a new Builder */
    private Builder() {
      super(SCHEMA$, MODEL$);
    }

    /**
     * Creates a Builder by copying an existing Builder.
     * @param other The existing Builder to copy.
     */
    private Builder(com.skaria.avro.model.aggregate.domain.UpdatePersonCommandRecord.Builder other) {
      super(other);
      if (isValidValue(fields()[0], other.Person)) {
        this.Person = data().deepCopy(fields()[0].schema(), other.Person);
        fieldSetFlags()[0] = other.fieldSetFlags()[0];
      }
      if (other.hasPersonBuilder()) {
        this.PersonBuilder = com.skaria.avro.model.Person.newBuilder(other.getPersonBuilder());
      }
    }

    /**
     * Creates a Builder by copying an existing UpdatePersonCommandRecord instance
     * @param other The existing instance to copy.
     */
    private Builder(com.skaria.avro.model.aggregate.domain.UpdatePersonCommandRecord other) {
      super(SCHEMA$, MODEL$);
      if (isValidValue(fields()[0], other.Person)) {
        this.Person = data().deepCopy(fields()[0].schema(), other.Person);
        fieldSetFlags()[0] = true;
      }
      this.PersonBuilder = null;
    }

    /**
      * Gets the value of the 'Person' field.
      * @return The value.
      */
    public com.skaria.avro.model.Person getPerson() {
      return Person;
    }

    /**
      * Gets the value of the 'Person' field as an Optional&lt;com.skaria.avro.model.Person&gt;.
      * @return The value wrapped in an Optional&lt;com.skaria.avro.model.Person&gt;.
      */
    public Optional<com.skaria.avro.model.Person> getOptionalPerson() {
      return Optional.<com.skaria.avro.model.Person>ofNullable(Person);
    }

    /**
      * Sets the value of the 'Person' field.
      * @param value The value of 'Person'.
      * @return This builder.
      */
    public com.skaria.avro.model.aggregate.domain.UpdatePersonCommandRecord.Builder setPerson(com.skaria.avro.model.Person value) {
      validate(fields()[0], value);
      this.PersonBuilder = null;
      this.Person = value;
      fieldSetFlags()[0] = true;
      return this;
    }

    /**
      * Checks whether the 'Person' field has been set.
      * @return True if the 'Person' field has been set, false otherwise.
      */
    public boolean hasPerson() {
      return fieldSetFlags()[0];
    }

    /**
     * Gets the Builder instance for the 'Person' field and creates one if it doesn't exist yet.
     * @return This builder.
     */
    public com.skaria.avro.model.Person.Builder getPersonBuilder() {
      if (PersonBuilder == null) {
        if (hasPerson()) {
          setPersonBuilder(com.skaria.avro.model.Person.newBuilder(Person));
        } else {
          setPersonBuilder(com.skaria.avro.model.Person.newBuilder());
        }
      }
      return PersonBuilder;
    }

    /**
     * Sets the Builder instance for the 'Person' field
     * @param value The builder instance that must be set.
     * @return This builder.
     */

    public com.skaria.avro.model.aggregate.domain.UpdatePersonCommandRecord.Builder setPersonBuilder(com.skaria.avro.model.Person.Builder value) {
      clearPerson();
      PersonBuilder = value;
      return this;
    }

    /**
     * Checks whether the 'Person' field has an active Builder instance
     * @return True if the 'Person' field has an active Builder instance
     */
    public boolean hasPersonBuilder() {
      return PersonBuilder != null;
    }

    /**
      * Clears the value of the 'Person' field.
      * @return This builder.
      */
    public com.skaria.avro.model.aggregate.domain.UpdatePersonCommandRecord.Builder clearPerson() {
      Person = null;
      PersonBuilder = null;
      fieldSetFlags()[0] = false;
      return this;
    }

    @Override
    @SuppressWarnings("unchecked")
    public UpdatePersonCommandRecord build() {
      try {
        UpdatePersonCommandRecord record = new UpdatePersonCommandRecord();
        if (PersonBuilder != null) {
          try {
            record.Person = this.PersonBuilder.build();
          } catch (org.apache.avro.AvroMissingFieldException e) {
            e.addParentField(record.getSchema().getField("Person"));
            throw e;
          }
        } else {
          record.Person = fieldSetFlags()[0] ? this.Person : (com.skaria.avro.model.Person) defaultValue(fields()[0]);
        }
        return record;
      } catch (org.apache.avro.AvroMissingFieldException e) {
        throw e;
      } catch (java.lang.Exception e) {
        throw new org.apache.avro.AvroRuntimeException(e);
      }
    }
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumWriter<UpdatePersonCommandRecord>
    WRITER$ = (org.apache.avro.io.DatumWriter<UpdatePersonCommandRecord>)MODEL$.createDatumWriter(SCHEMA$);

  @Override public void writeExternal(java.io.ObjectOutput out)
    throws java.io.IOException {
    WRITER$.write(this, SpecificData.getEncoder(out));
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumReader<UpdatePersonCommandRecord>
    READER$ = (org.apache.avro.io.DatumReader<UpdatePersonCommandRecord>)MODEL$.createDatumReader(SCHEMA$);

  @Override public void readExternal(java.io.ObjectInput in)
    throws java.io.IOException {
    READER$.read(this, SpecificData.getDecoder(in));
  }

  @Override protected boolean hasCustomCoders() { return true; }

  @Override public void customEncode(org.apache.avro.io.Encoder out)
    throws java.io.IOException
  {
    this.Person.customEncode(out);

  }

  @Override public void customDecode(org.apache.avro.io.ResolvingDecoder in)
    throws java.io.IOException
  {
    org.apache.avro.Schema.Field[] fieldOrder = in.readFieldOrderIfDiff();
    if (fieldOrder == null) {
      if (this.Person == null) {
        this.Person = new com.skaria.avro.model.Person();
      }
      this.Person.customDecode(in);

    } else {
      for (int i = 0; i < 1; i++) {
        switch (fieldOrder[i].pos()) {
        case 0:
          if (this.Person == null) {
            this.Person = new com.skaria.avro.model.Person();
          }
          this.Person.customDecode(in);
          break;

        default:
          throw new java.io.IOException("Corrupt ResolvingDecoder.");
        }
      }
    }
  }
}










